ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: true
    publish_tf: true
    publish_acceleration: false
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /odom
    odom0_config: [true, true, true,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false]
    odom0_queue_size: 10

    imu0: /imu/data
    imu0_config: [false, false, false,
                  true, true, true,
                  true, true, true,
                  false, false, false,
                  false]
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    dvl0: /dvl/twist
    dvl0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, false,
                  false]
    dvl0_queue_size: 10

    process_noise_covariance: [0.05, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.05, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.05, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.05, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.05, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.05]

    initial_estimate_covariance: [1e-9, 0.0, 0.0, 0.0, 0.0, 0.0,
                                  0.0, 1e-9, 0.0, 0.0, 0.0, 0.0,
                                  0.0, 0.0, 1e-9, 0.0, 0.0, 0.0,
                                  0.0, 0.0, 0.0, 1e-9, 0.0, 0.0,
                                  0.0, 0.0, 0.0, 0.0, 1e-9, 0.0,
                                  0.0, 0.0, 0.0, 0.0, 0.0, 1e-9]

    imu0_linear_acceleration_rejection_threshold: 0.8
    imu0_nodal_velocity_rejection_threshold: 0.8
    odom0_rejection_threshold: 2.0
